// Sample Configuration File for Shairport Sync
// Commented out by default - uncomment to enable

// general = {
// name = "Campfire Bridge";
// password = "secret";
// interpolation = "soxr";
// };

// sessioncontrol = {
// allow_session_interruption = "yes";
// session_timeout = 10;
// };
